### ISSUE TITLE
webpack warning

### ISSUE THREAD

**Issue by liorsharabi** [nfriend/ts-keycode-enum#1]
WARNING in ./~/ts-keycode-enum/dist/js/Key.enum.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

**Comment by nfriend** [comment]
Thanks for reporting this, @liorsharabi.  What version of Webpack are you using?

**Comment by liorsharabi** [comment]
2.2.1

**Comment by nfriend** [comment]
@liorsharabi I have been testing with Webpack 1, which I'm guessing might be why I'm not seeing the warning myself.  I just changed the TypeScript build to output a CommonJS module instead of a UMD module, which I think will fix the issue.  Can you install the latest version (1.0.3) and let me know if that solves the issue?

**Comment by liorsharabi** [comment]
still the same error:/

**Comment by liorsharabi** [comment]
still the same error:/ 
used 1.0.3

**Comment by nfriend** [comment]
@liorsharabi Ok, sorry, I just realized my last commit didn't actually have any effect.  I just republished the module as 1.0.4 and confirmed that my changes made it into the package - let me know if this one works for you.

**Comment by liorsharabi** [comment]
it's working now
thanks:)
