### ISSUE TITLE
remove js code

### ISSUE THREAD

**Issue by theGABS** [nfriend/ts-keycode-enum#2]
typescript enum exist in runtime, but you can add keyword const like
```
const enum Directions {
    Up,
    Down,
    Left,
    Right
}
```
and then its full remove from js. Maybe its be better?

**Comment by nfriend** [comment]
Hi @theGABS, thanks for the suggestion.  The advantage of having the enum exist at runtime is that you can query the enum for the description of the keycode:

```TypeScript
import { Key } from 'ts-keycode-enum';

console.log(Key[8]); // logs "Backspace"
```

which can be useful in certain cases.

Although I do think it would be valuable to have a `const` version of this module for those that don't use this functionality and would rather use the enum without the extra `.js` in their output.  I'm going to close this issue for now, since I won't be making this change to this module, but I'll consider creating a new module for this use case.
